/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Toast } from "./components/mini-toast-service/index";
export { Toast } from "./components/mini-toast-service/index";
export namespace Components {
    interface MiniToast {
        "closeable": boolean;
        "duration": number;
        "icon": string;
        "message": string;
        "position": 'top' | 'bottom' | 'left' | 'right';
        "showClose": boolean;
        "type": 'success' | 'error' | 'warning' | 'info';
    }
    interface MiniToastService {
        "show": (toast: Toast) => Promise<void>;
    }
}
declare global {
    interface HTMLMiniToastElement extends Components.MiniToast, HTMLStencilElement {
    }
    var HTMLMiniToastElement: {
        prototype: HTMLMiniToastElement;
        new (): HTMLMiniToastElement;
    };
    interface HTMLMiniToastServiceElement extends Components.MiniToastService, HTMLStencilElement {
    }
    var HTMLMiniToastServiceElement: {
        prototype: HTMLMiniToastServiceElement;
        new (): HTMLMiniToastServiceElement;
    };
    interface HTMLElementTagNameMap {
        "mini-toast": HTMLMiniToastElement;
        "mini-toast-service": HTMLMiniToastServiceElement;
    }
}
declare namespace LocalJSX {
    interface MiniToast {
        "closeable"?: boolean;
        "duration"?: number;
        "icon"?: string;
        "message"?: string;
        "position"?: 'top' | 'bottom' | 'left' | 'right';
        "showClose"?: boolean;
        "type"?: 'success' | 'error' | 'warning' | 'info';
    }
    interface MiniToastService {
    }
    interface IntrinsicElements {
        "mini-toast": MiniToast;
        "mini-toast-service": MiniToastService;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mini-toast": LocalJSX.MiniToast & JSXBase.HTMLAttributes<HTMLMiniToastElement>;
            "mini-toast-service": LocalJSX.MiniToastService & JSXBase.HTMLAttributes<HTMLMiniToastServiceElement>;
        }
    }
}
