/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MiniToast {
        "duration": number;
        "message": string;
        "showToast": (message: string, type?: string) => Promise<void>;
        "type": 'success' | 'error' | 'warning' | 'info';
    }
}
declare global {
    interface HTMLMiniToastElement extends Components.MiniToast, HTMLStencilElement {
    }
    var HTMLMiniToastElement: {
        prototype: HTMLMiniToastElement;
        new (): HTMLMiniToastElement;
    };
    interface HTMLElementTagNameMap {
        "mini-toast": HTMLMiniToastElement;
    }
}
declare namespace LocalJSX {
    interface MiniToast {
        "duration"?: number;
        "message"?: string;
        "type"?: 'success' | 'error' | 'warning' | 'info';
    }
    interface IntrinsicElements {
        "mini-toast": MiniToast;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mini-toast": LocalJSX.MiniToast & JSXBase.HTMLAttributes<HTMLMiniToastElement>;
        }
    }
}
